### ISSUE TITLE
UI: List Items responsiveness

### ISSUE THREAD

**Issue by TiagoV-PDMFC** [PharmaLedger-IMI/fgt-workspace#19]
List items ahould, when the screen is small enough, change the number of items they show (until they show only the '...' buttons.

The WebComponent list-item-layout already has information about the current screen size. Use that to add logic to list elements so they change the displayCount variable they pass to the pdm-item-organizer WebComponent accordingly and ensure that even on a small screen, list items dont overlap.

Changes to the list-item-layout might be required, but should be discussed beforehand.

Also, while at it, correct some minor UI bugs that you find. Ex: In the mah wallet, the managed-shipment-line-list-item cuts the label that identifies the sender/receiver (and the labels positions are swapped)

**Comment by pccosta-pdm** [comment]
the bugs reported by @VNogueira91 was out of scope of this issue, however was fixed by three commits above, because were minor fixes.

On 2nd commit "add disabled property to product input when...", on the future, probably will needed add some validation on select product (from both sides, MAH and WHS), or a dropdown that search a pre-defined list of products, according comment on commit: "using the event listener "onChange", can spawn more issues, because to approve an order on the MAH, more validations would be needed."
