### ISSUE TITLE
Partner Onboarding

### ISSUE THREAD

**Issue by TiagoV-PDMFC** [PharmaLedger-IMI/fgt-workspace#43]
Refactor current SSApps to function as api endpoints

**Comment by TiagoV-PDMFC** [comment]
The fact that we mean to remove the Order DSU from the equation (and completely remove order logic from pharmaledger... it should exist only in the ERPs) imposes an issue since the shipment confirmation is done via the order API a refactor is needed (that I somehow missed).

The best option is to:
use the same status DSU, and index it differently on the received side (it would mean 2 distinct users update a single status DSU, which, without inbuilt DSU validation, is not so cool, but will work)
mantain the duplication of status DSUs, but move that logic to 'incoming' shipments. This is the solution closest to the existing one.

To be discussed

**Comment by pccosta-pdm** [comment]
Some Notes:
- Add saleId on sale model. The wallet application generates saleId automatically.
- A sale can be performed more than once, even without Stock.
- When perform a sale, the productList data is persisted without question, instead of being consistently populated (such as name,  status, etc.)
- On shipment endpoint, it's needed a partnerId and orderId. I think would be desirable that partnerId was implicit.
- When create a shipment, the _ShipmentLine.status_ is mandatory. This should not be filled from/as _Shipmen.status_?
- In some cases, the Manager.getPage not provide "itemsPerPage"
- Traceability API is returned data to be consume by UI/Wallet App, instead a "usable" data.
- status is mandatory to create a Shipment. Should be exist a status default, but can cause update conflict (it's not mandatory because on the Wallet, the status come from Order) Related to #44

**Comment by TiagoV-PDMFC** [comment]
Comments:
- Functionality seems to be working as expected minus:
  - receipt and sale enumeration in pharmacies is not working:
  - error messages are always the same "Not implemented" despite having different codes
- Breaks the environment-trace script (I tested in master and got no errors, tested twice in the branch and got errors both times)

**Comment by pccosta-pdm** [comment]
- when request a shipment to MAH, for requester side, the stock is incremented. It's happens because the DSU is "duplicated" on the both sides.
- SaleManager after performed, is adding to stock instead of remove. Suggestion:
	- Batch model calcs the quantity and apply the signal in the end of calc
	- create specific method for each operation (one to add and another to remove from stock)
- MAH doesn't check if the serialNumber belongs to it, it just adds the sale and receipt
- PHA accepts to create a shipment, it's happens because the all participants share a "default api". To solve it, the "default api" needs to accept a injection of allowed HTTP methods


> Comments:
> 
>   * receipt and sale enumeration in pharmacies is not working:

Sale is working properly on the PHA side, but the receipt only on MAH side.

>   * error messages are always the same "Not implemented" despite having different codes

The custom errors is only implemented in the /shipment route (that works with a specific version of shipment for API). It's need to discuss what approach is preferable.

> * Breaks the environment-trace script (I tested in master and got no errors, tested twice in the branch and got errors both times)

A validation was added to ShipmentService. In a nutshell: 
**before:** err = shipment.validate(); **after:** err = shipment.validate(shipmentOldStatus);

The environment-trace has a timeout to make the updates, that probably is conflicting with asynchronism and updating shipments twice (on the master, check for received shipments status log).

**Comment by TiagoV-PDMFC** [comment]
Overall functionality is working.

Great job on implementing the swagger apis interface.

merged to master
