### ISSUE TITLE
Re-scale the list items (especially the ones with the item organizer component) to a more conservative ratio so they only always occupy one line on the screen

### ISSUE THREAD

**Issue by TiagoV-PDMFC** [PharmaLedger-IMI/fgt-workspace#48]

**Comment by pccosta-pdm** [comment]
@TiagoV-PDMFC the line break issue has been solved, however some "anomalies" may still occur, due to the fact that there is no table itself, but a set of non-standardized rows/columns/grid, that involve other components (and would be costl to update it) and that I think is not a priority for now, but let me know your opinion.

below what i mean:
![image](https://user-images.githubusercontent.com/81983397/140794730-0546406b-b23d-4eca-9ada-aff01c1b8ecf.png)

![image](https://user-images.githubusercontent.com/81983397/140795215-e9c51572-1b41-446f-9b13-870e4d83ab44.png)

**Comment by pccosta-pdm** [comment]
@lehialessandro to give your help, I created a branch (refs48_itemListResizing) with the last commit to check the problem with grid/resizing

**Comment by pccosta-pdm** [comment]
@lehialessandro looks good to me, @TiagoV-PDMFC, anything to add?

**Comment by pccosta-pdm** [comment]
new features will be implemented on #51
