### ISSUE TITLE
Implement Table filtering by search

### ISSUE THREAD

**Issue by TiagoV-PDMFC** [PharmaLedger-IMI/fgt-workspace#49]
The search bar on the pdm-ion-table is currently useless.
The managers have a method called 'keywordToQuery';

phase 1: Implement the logic that connects the two: think google like logic. you insert a keyword, the manager, via the keywordToQuery method translates that into an overall search: imagine, for the product table a keyword should be translated to gtin or product name. This imples making an 'OR' query, which is basically making more that one query, and eliminating duplicates. There is no API for this in the managers currently. only 'AND' queries are supported natively by the DB query mechanisms;

Phase 2 (mega low pri): refactor the search bar to integrate with the manager's index fields and allow for complex queries with multiple keywords

**Comment by TiagoV-PDMFC** [comment]
This was requested by the partners and is without a doubt a useful feature for UI reasons (and also to have access to an 'OR' query logic

**Comment by pccosta-pdm** [comment]
p.s.: the search bar performs the search through the manager's indexes. It was decided that more complex and selective logic will be implemented in the future.

**Comment by TiagoV-PDMFC** [comment]
Table Filtering seems to be:
 - working properly for products, orders, shipments, shipmentlines, receipts, and stock;
 
 but:
 - not showing up the search bar for batches;
 - not working when you click enter;
 - does not clean search when you click the 'x' to clear the search bar;

Will merge to master. When you have the time come back to this, and fix these minor details

**Comment by pccosta-pdm** [comment]
search bar issues fixed and merged to master.

**Comment by pccosta-pdm** [comment]
There is a issue with "getPage" on main manager:

Query by keyword uses the manager/table indexes and perform a search for each index
There is an issue when a composite key it's needed.

e.g.: Batch - to found a batch properly it's needed the GTIN and BatchNumber. So in the ProductManage that list all batches of a single product, when table loads or query by search bar, it's needed to include GTIN (as a mandatory field to ensure data integrity) + keyword query, otherwise the query will return results that not belongs to that GTIN.
