### ISSUE TITLE
Implement Table Headers

### ISSUE THREAD

**Issue by TiagoV-PDMFC** [PharmaLedger-IMI/fgt-workspace#51]
As requested by the partners, we should have table headers (at least for the non mobile versions)

Maybe we can use the indexes property on each of the managers passed to the pdm-ion-table to, through order correclty display the table headers

**Comment by pcesar-costa** [comment]
@VNogueira91  Some issues found:
- On manage product (product -> eye button). Table header is not being shown.
![image](https://user-images.githubusercontent.com/23053575/149772762-dbdde112-9c09-4c78-89f6-6e439dea2542.png)

- On orders, the "order lines" colum is not align with the data. Probably because there are a extra margin on template
![image](https://user-images.githubusercontent.com/23053575/149773071-581915cb-a716-4efc-9ec9-2323ddfae143.png)

- On ShipmentLines, I would put a highlight on dropdown or second header, it's confusing to read
![image](https://user-images.githubusercontent.com/23053575/149774462-56634b79-2693-40c9-bf6f-e6d949d2c304.png)

- Some column headers of "Serial Number" has different abbreviation
![image](https://user-images.githubusercontent.com/23053575/149775226-2dabb074-cdc9-420c-881a-154dd82d2550.png)
![image](https://user-images.githubusercontent.com/23053575/149775333-762bbc91-83c9-43f4-b487-1601787e8fa8.png)

The functionality looks good, just some UI fixes. Good job.

**Comment by TiagoV-PDMFC** [comment]
You need to look more in depth at the code. Get buttons returns an array, not a singe element

**Comment by TiagoV-PDMFC** [comment]
Not perfect, but perfectly usable for now
